INSERT INTO tb_cartoon_list (name) VALUES ('Adventure');
INSERT INTO tb_cartoon_list (name) VALUES ('Comedy');

INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description)VALUES ('Hora de Aventura', 4.4, 2010, 'Adventure, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/adventuretime.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Apenas um Show', 4.0, 2010, 'Adventure, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/apenas-um-show.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Coragem, o Cão Covarde', 4.0, 1999, 'Adventure, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/coragem.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('O Laboratório de Dexter', 3.6, 1996, 'Comedy, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/dexter.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Du, Dudu e Edu', 3.2, 1999, 'Comedy, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/dudududu.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Gravity Falls: Um Verão de Mistérios', 4.5, 2012, 'Adventure, Animation', 'Disney+', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/gravityfalls.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('O Incrível Mundo de Gumball', 4.3, 2011, 'Comedy, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/gumbal.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Historietas Assombradas (para Crianças Malcriadas)', 3.2, 2013, 'Adventure, Animation', 'Youtube', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/Historietas-Assombradas.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('A Mansão Foster Para Amigos Imaginários', 4.2, 2004, 'Comedy, Animation', 'HBO Max', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/mansaofoster.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');
INSERT INTO tbl_Cartoon (title, score, cartoon_year, genre, platforms, img_url, short_description, long_description) VALUES ('Pocoyo', 3, 2005, 'Comedy, Animation', 'Prime Video, Globoplay', 'https://raw.githubusercontent.com/Kalebits/dslist/main/src/main/resources/img/pocoyo.png', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Odit esse officiis corrupti unde repellat non quibusdam! Id nihil itaque ipsum!', 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Delectus dolorum illum placeat eligendi, quis maiores veniam. Incidunt dolorum, nisi deleniti dicta odit voluptatem nam provident temporibus reprehenderit blanditiis consectetur tenetur. Dignissimos blanditiis quod corporis iste, aliquid perspiciatis architecto quasi tempore ipsam voluptates ea ad distinctio, sapiente qui, amet quidem culpa.');

INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (1, 6, 3);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (1, 8, 4);

INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (2, 4, 0);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (2, 5, 1);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (2, 7, 2);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, cartoon_id, position) VALUES (2, 10, 4);